GET   http://localhost:8000/api/user/profile

###
GET   http://localhost:8000/api/user/token

###
POST  http://localhost:8000/api/user/login
Content-Type: application/json

{
    "email": "rifqi@123.com",
    "password": "123456"
}

###
GET  http://localhost:8000/api/user/refreshToken

###
POST  http://localhost:8000/api/user/register
Content-Type: application/json

{ 
    "name":"rifqi",
    "email" : "rifqi@123.com", 
    "address": "rumah", 
    "password": "123456" 
}

###
DELETE   http://localhost:8000/api/user/logout

###
GET  http://localhost:8000/api/kelas/getKelas

###
POST  http://localhost:8000/api/kelas/addKelas
Content-Type: application/json

{ 
    "title":"kelas rifqi 4",
    "pathImg" : "/images/assets/emosi253x143.png"
}
###
GET  http://localhost:8000/api/props/getProps

###
POST  http://localhost:8000/api/props/addPaket
Content-Type: application/json

{
    "img": "/images/assets/paketkonsul (1).png",
    "pic": "Bersama Konselor",
    "title": "Konsultasi Via Chat",
    "desc": "Konsultasi dengan nyaman dan tenang layaknya teman curhat melalui chating",
    "price": 15000,
    "isFav": 0
}

###
POST  http://localhost:8000/api/props/addTesti
Content-Type: application/json

{
    "img": "",
    "name": "Doe Fulan 4",
    "desc": "uod Enchiridion Epictetus stoici scripsit. Rodrigo Abela et Technologiae apud Massachusetts instituta Opera collectio. Ex anglicus latine translata sunt.Quidam alii sunt, et non est in nostra potestate. Quae",
    "role": "Mahasiswa"
}
###
POST  http://localhost:8000/api/props/addKonselor
Content-Type: application/json

{
    "img": "",
    "name": "Doe Afwan 5",
    "desc": "uod Enchiridion Epictetus stoici scripsit. Rodrigo Abela et Technologiae apud Massachusetts instituta Opera collectio. Ex anglicus latine translata sunt.Quidam alii sunt, et non est in nostra potestate. Quae",
    "role": "Konselor"
}